# Generated by Django 5.1 on 2024-08-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('MATH', 'Math Game'), ('ANAGRAM', 'Anagram Game')], default='MATH'),
        ),
    ]
