# Generated by Django 5.1 on 2024-08-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamescore_settings_alter_gamescore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='settings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
