# Generated by Django 4.0.5 on 2024-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='settings',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscore',
            name='type',
            field=models.TextField(default='default_type', max_length=100),
            preserve_default=False,
        ),
    ]
